project:
  type: book
  output-dir: docs

book:
  title: "Análisis TFG"
  author: "Marcos Oliva"
  date: last-modified
  reader-mode: true
  page-footer:
    left: |
      Análisis TFG
    right: |
     Este libro se ha creado con  <a href="https://quarto.org/">Quarto</a>.
  favicon: images/quarto2.png
  site-url: https://marcosolivamunoz.github.io/analisis_TFG
  repo-url: https://github.com/MarcosOlivaMunoz/analisis_TFG
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - contexto.qmd
    - analisis_exploratiorio.qmd

format:
  html:
    include-in-header: 
    - text: |
      <link rel="icon" type="image/png" href="images/quarto2.png" sizes="96x96" />
    theme: cosmo
    lang: es 